stages:
  - build
  # - test

# The Docker image that will be used to build your app
image: node:latest
# Functions that should be executed before the build script is run

build:
  stage: build
  before_script:
  - npm ci
  script:
    - npm run prod-build
  artifacts:
    paths:
      - node_modules
      - server.js
      - public

test:
  stage: test
  script:
    - npm run test
